Ensure ansible-pacemaker is present on the undercloud.
On upstream CI in mixed upgrade the undercloud doesn't have this
package by default.

This make the ffu upgrade fail during ffu_upgrade_playbook with:

  exception: no action detected in task. This often indicates a
  misspelled module name, or incorrect module path.

This make sure that this package is installed as it should on "normal"
installation.

Change-Id: Ic3268aa1c0fb84d0039395186861e9dea838a6e3