Ensure bc package is installed for l3 ping tests.
When running the l3 ping tests we get the following
error: bc: command not found.
Let's make sure the package is present in the system
when generating the scripts.

Change-Id: I32ad402dc7e42d85e574bf1273664bc7d6d1f9a5
(cherry picked from commit 359eb6b82718ab2506d7ba63d116e7a2ce3a3211)
(cherry picked from commit d466df618af889b624cb0457d32175f9794df2a5)