Ensure ansible-pacemaker is present on the undercloud.
On upstream CI in mixed upgrade the undercloud doesn't have this
package by default.

This make the ffu upgrade fail during ffu_upgrade_playbook with:

  exception: no action detected in task. This often indicates a
  misspelled module name, or incorrect module path.

This make sure that this package is installed as it should on "normal"
installation.

Furthermore it directly includes the fix from
Id87a40c3f41ca6da2d449e891b1f05d2705d3909.

Change-Id: Ic3268aa1c0fb84d0039395186861e9dea838a6e3
(cherry picked from commit d195142ac546250a2df60ee1dc9ad7cfd78948af)